/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package update.dependencies;

import java.util.List;
import java.util.Map;
import lombok.extern.slf4j.Slf4j;
import update.dependencies.app.execute.ExecuteScript;
import update.dependencies.app.model.ScriptFile;
import update.dependencies.app.util.AppInitUtil;

@Slf4j
public class App {
  public static void main(String[] args) {
    log.info("Begin dependencies-update initialization...");

    Map<String, String> argsMap = AppInitUtil.makeArgsMap(args);
    List<ScriptFile> scriptFiles = AppInitUtil.getScriptsInResources();

    executeNpmScripts(argsMap, scriptFiles);

    log.info("End dependencies-update initialization...");
  }

  private static void executeNpmScripts(Map<String, String> argsMap, List<ScriptFile> scriptFiles) {
    scriptFiles.forEach(
        scriptFile -> {
          ExecuteScript executeScript =
              new ExecuteScript(scriptFile.getScriptFileName(), argsMap, scriptFile);
          Thread esThread = executeScript.start();
          while (esThread.isAlive()) {
            threadSleep();
          }
        });
  }

  private static void threadSleep() {
    try {
      Thread.sleep(1000);
      log.info(".");
    } catch (InterruptedException ex) {
      log.error("Error in thread sleep", ex);
    }
  }
}
