/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nospring.service.skeleton;

import lombok.extern.slf4j.Slf4j;
import nospring.service.skeleton.app.server.ServerJetty;

@Slf4j
public class App {
  public static void main(String[] args) throws Exception {
    log.info("Begin nospring-service-skeleton initialization...");
    new ServerJetty().start();
    log.info("End nospring-service-skeleton initialization...");
  }
}
